[build]
  # Build command
  command = "pnpm run build"
  
  # Publish directory (Next.js output)
  publish = ".next"
  
  # Node.js version
  [build.environment]
    NODE_VERSION = "18"
    NPM_FLAGS = "--version"
    PNPM_VERSION = "8"

[build.processing]
  # Skip processing for certain file types
  skip_processing = false

[build.processing.css]
  # Bundle CSS files
  bundle = true
  # Minify CSS
  minify = true

[build.processing.js]
  # Bundle JavaScript files
  bundle = true
  # Minify JavaScript
  minify = true

[build.processing.html]
  # Pretty URLs (remove .html extension)
  pretty_urls = true

[build.processing.images]
  # Optimize images
  compress = true

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Performance headers
    X-DNS-Prefetch-Control = "on"

# Headers for static assets (caching)
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Headers for fonts
[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.otf"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Headers for CSS and JS
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirects for Next.js
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Build settings
[build.settings]
  # Functions directory
  functions = "netlify/functions"
  
  # Edge functions directory
  edge_functions = "netlify/edge-functions"

# Environment variables (set these in Netlify dashboard)
# [build.environment]
#   NEXT_PUBLIC_SITE_URL = "https://your-site.netlify.app"
#   NEXT_PUBLIC_API_URL = "https://your-api.com"

# Form handling
[build.processing.skip_processing]
  # Skip processing for certain paths
  paths = ["/admin/*", "/api/*"]

# Build hooks (optional)
# [build.hooks]
#   pre_build = "echo 'Starting build...'"
#   post_build = "echo 'Build completed!'"
